CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  size TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  address TEXT NOT NULL,
  created_at TEXT NOT NULL
);
